version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/app
    steps:
      - checkout
      - run: mvn test
      

workflows:
  version: 2.1
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
