version: 2.1

jobs:
  build:
    # image to run test from
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: /pom
    steps:
      - checkout  # copy the project into image
      - run: mvn test
      

workflows:
  version: 2.1
  # only run the master branch
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
